# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wepaly',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/wepaly',
                'lib_path': 'wepaly'},
  'syms': {'wepaly.core': {'wepaly.core.foo': ('core.html#foo', 'wepaly/core.py')}}}
